apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage-layer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/SimonYYL/pi-data-platform.git
    targetRevision: HEAD
    path: infra/storage
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true