apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.5.3
    helm:
      parameters:
        - name: persistence.defaultClassReplicaCount
          value: "2"
        - name: defaultSettings.createDefaultDiskLabeledNodes
          value: "true"
        - name: csi.attacher.replicaCount
          value: "1"
        - name: csi.provisioner.replicaCount
          value: "1"
        - name: csi.resizer.replicaCount
          value: "1"
        - name: csi.snapshotter.replicaCount
          value: "1"
        - name: helmPreUpgradeCheckerJob.enabled
          value: "false"
        # --- NEW FIX BELOW ---
        - name: csi.kubeletRootDir
          value: "/var/lib/kubelet"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true