apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.5.3
    helm:
      parameters:
        - name: persistence.defaultClassReplicaCount
          value: "2"  # Keep 2 copies of data (saves space on small cluster)
        - name: defaultSettings.createDefaultDiskLabeledNodes
          value: "true"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true