apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minio
  namespace: argocd
  # --- NEW SECTION STARTS HERE ---
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  # --- NEW SECTION ENDS HERE ---
spec:
  project: default
  source:
    chart: minio
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 14.6.1
    helm:
      parameters:
        - name: image.registry
          value: "docker.io"
        - name: image.repository
          value: "minio/minio"
        - name: image.tag
          value: "RELEASE.2024-11-07T00-52-20Z"
        - name: auth.rootUser
          value: "admin"
        - name: auth.rootPassword
          value: "minioadmin"
        - name: mode
          value: "standalone"
        - name: resources.limits.memory
          value: "512Mi"
        - name: persistence.storageClass
          value: "longhorn"
        - name: persistence.size
          value: "10Gi"
        - name: metrics.enabled
          value: "false"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: minio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true